// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Drew_Jensen_Week_14_Assignment.Models
{
    public partial class Student
    {
        // woopsy daisies
        // woopsy daisies
        public Student()
        {
            StudentSchedules = new HashSet<StudentSchedule>();
        }

        public string StudentId { get; set; }
        public string StudFirstName { get; set; }
        public string StudLastName { get; set; }
        public string StudMajor { get; set; }
        public string StudPhone { get; set; }

        public virtual ICollection<StudentSchedule> StudentSchedules { get; set; }
    }
}