// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Drew_Jensen_Week_14_Assignment.Models
{
    public partial class Subject
    {
        public Subject()
        {
            Classes = new HashSet<Class>();
        }

        public string SubjectId { get; set; }
        public string ClassId { get; set; }
        public string SubjectCode { get; set; }
        public string SubjectName { get; set; }
        public string SubjectDescription { get; set; }

        public virtual Class Class { get; set; }
        public virtual ICollection<Class> Classes { get; set; }
    }
}